### ISSUE TITLE
v1.1.3 🙏

### ISSUE THREAD

**Issue by nshiab** [duckdb/duckdb-node#138]
Hi! Would it be possible to update to the latest version of duckdb?

Thank you 🙏

**Comment by nshiab** [comment]
@carlopi, it looks like the publishing on NPM failed...

<img width="1502" alt="Screenshot 2024-11-12 at 10 40 00 AM" src="https://github.com/user-attachments/assets/145d8b69-bca3-4a88-996d-6853cbd62f64">

**Comment by nshiab** [comment]
It's still v1.1.1 on NPM.

<img width="1196" alt="Screenshot 2024-11-12 at 10 41 04 AM" src="https://github.com/user-attachments/assets/710e4934-3834-4e45-bf89-4133bc1572ba">

**Comment by carlopi** [comment]
Thanks, I know, I messed up some minor stuff in deploy, looking at this, to be solved in the next hours.

**Comment by nshiab** [comment]
Thank you!

**Comment by carlopi** [comment]
It's should be out, thanks!

**Comment by nshiab** [comment]
It works! Thanks a lot, @carlopi !
