### ISSUE TITLE
BIGINT response issue after upgrading from 0.8.0

### ISSUE THREAD

**Issue by thomascmurphy** [duckdb/duckdb-node#26]
Howdy! We are trying to upgrade from 0.8.0 to 0.9.1 and are trying to figure out how to deal with a breaking change that popped up. We are doing some pretty simple queries on parquet files, and for columns of type BIGINT we are seeing the result being an actual `bigint` JS type whereas previously there were just type `number`. So, response from a simple `db.all("SELECT * FROM read_parquet('.../someFile.parquet')", (err: any, rows: TableData) => { ... })` results in the rows being:

0.8.X
`[
    { col1: 1, col2: 2, col3: 4 },
    { col1: 2, col2: 5, col3: 15 },
    { col1: 3, col2: 9, col3: 81 }
  ]`
  
 0.9.1
 `[
    { col1: 1n, col2: 2n, col3: 4n },
    { col1: 2n, col2: 5n, col3: 15n},
    { col1: 3n, col2: 9n, col3: 81n }
  ]`

I don't see anything listed in the migration guide that would indicate a change resulting in this behavior, is it a known thing? Also just tested with other types and INTEGER/HUGEINT actually work as expected, so for now we can swap to HUGEINT...just figured I should bring it up.

**Comment by thomascmurphy** [comment]
Actually getting the same behavior as a result of "read_csv_auto" with integer values, so that will be a blocker for us I suppose.

**Comment by thomascmurphy** [comment]
Cross-posted in the main repo with the repro steps as well: https://github.com/duckdb/duckdb/issues/9586

**Comment by Mause** [comment]
Resolved in main repo
