### ISSUE TITLE
No tag for `0.10.0` release

### ISSUE THREAD

**Issue by zenazn** [duckdb/duckdb-node#47]
I'd expect a git tag for the 0.10.0 release—perhaps pointing at commit 03a403d82910ec116a59cd66d027b041f2bbc0a7—but it seems like one hasn't been made yet.

**Comment by zenazn** [comment]
Actually, it seems like there hasn't been a release at all! Any news on when we can expect one? https://www.npmjs.com/package/duckdb?activeTab=versions

**Comment by archiewood** [comment]
it appears [there are some CI failures](https://discord.com/channels/909674491309850675/921125471905787944/1207699563415076924) the team is still working through

**Comment by carlopi** [comment]
Commit a62d096 has been tagged as v0.10.0, and it's also available on npm: https://www.npmjs.com/package/duckdb/v/0.10.0
