### ISSUE TITLE
`npm i duckdb` stays stuck?

### ISSUE THREAD

**Issue by nshiab** [duckdb/duckdb-node#81]
Hi!

Since this morning, it looks like installing duckdb doesn't work with npm.

When running this command, it stays stuck forever.

<img width="874" alt="Screenshot 2024-04-25 at 9 02 55 AM" src="https://github.com/duckdb/duckdb-node/assets/11160343/a0f27042-dd79-40c0-b88b-740484911d25">

All NPM systems are operational. I installed other libraries without any problem, including duckdb wasm.

Any idea what's going on?

Cheers

**Comment by GllmR** [comment]
It seems to be related to Apple M1 or ARM:
- I have the same bug on my macbook pro (M1 pro)
- I can install duckdb on my debian sid computer without problems

**Comment by nshiab** [comment]
Ah! I have an M1 pro too.

**Comment by GllmR** [comment]
> Ah! I have an M1 pro too.

You can install the previous 0.10.1 version.

**Comment by carlopi** [comment]
GitHub was not super reliable yesteday, some builds have been properly uploaded only this morning.

This is the CI run: https://github.com/duckdb/duckdb-node/actions/runs/8829385865

Can you double check ?

**Comment by nshiab** [comment]
Working! Thanks @carlopi !
