### ISSUE TITLE
Problems with v0.10.2 build for OSX x64

### ISSUE THREAD

**Issue by jchang-sensorup** [duckdb/duckdb-node#84]
It appears as though the v0.10.2 build for OSX x64 is not producing the expected x64 artifact.

For example, "node.js OSX (x64, 18, true)":
https://github.com/duckdb/duckdb-node/actions/runs/8829385865/job/24288862506

<img width="1598" alt="Screenshot 2024-05-02 at 11 51 33 AM" src="https://github.com/duckdb/duckdb-node/assets/41073648/6d1e103f-4270-46d1-bf88-f0250af5bc26">

The log indicates that the target arch is `x64`, as expected, but later on in the log, it appears as though the build is actually targeting `arm64` instead.

Further, when trying to use the DuckDB Node Bindings v0.10.2 on an Intel Mac, an error is caused indicating that `duckdb.node` is a "(mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h' or 'x86_64')". Note that this error does not occur when using v0.10.1.

The Linux x64 builds do not seem to be affected by a similar problem.

**Comment by carlopi** [comment]
Thanks for raising this, I think I have a solution, sending a PR later today.
