### ISSUE TITLE
Error: dlopen tried: /duckdb.node (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64h'))

### ISSUE THREAD

**Issue by archiewood** [duckdb/duckdb-node#92]
A user of ours (Evidence) is encountering an error when installing duckdb on their intel mac.

node 20.12.0
Mac 2.3GHz Core i5 Intel

they were able to reproduce the error installing in a fresh npm project with just duckdb dep

i suspect a missing or incorrect binary?

**Comment by carlopi** [comment]
I though this was solved by this PR: https://github.com/duckdb/duckdb-node/pull/88, what duckdb-node version are they on?

I would expect development version of node to solve the problem, now also a more proper test is included in CI, or bumping back to node v0.10.1, if that's a possibility.

DuckDB node next version will be tagged tomorrow.

**Comment by archiewood** [comment]
this was on 0.10.2
